### ISSUE TITLE
Missing changelog in the RPM Spec

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/iotagent-ul#144]
The RPM spec did not have any changelog until the 1.2 version. In that version, the changes from the version itself were introduced, but the past changes were not. These should be completed to have a complete changelog of the product in the RPM.

**Comment by Keshav-NEC** [comment]
Hi @dmoranj are you talking about ```rpm/SPECS/iotaul.spec```.

Hi @fgalan if updation is done in RPM Spec can we ask @dmoranj to close the issue?

**Comment by fgalan** [comment]
RPM are no longer used to build IOTAs (in favour of Docker containers).

Note we have yet rpm/SPEC/iotaul.spec but only for Changelog purposes. In the future the changelog in rpm/SPEC/iotaul.spec file should be moved to a proper Changelog file (as we did in the fiware-orion repository time ago).

This issue can be closed.
