### ISSUE TITLE
MQTT Secure SSL/TLS

### ISSUE THREAD

**Issue by caiothomas** [telefonicaid/iotagent-ul#148]
Dear Friends,

The iotagent-ul supports MQTT Secure SSL/TLS?

Thanks,
Caio Thomas

**Comment by dmoranj** [comment]
In all the current deployments of the IoTAgent, the MQTT Broker has been installed either in the same machines as the IoTA itself, or in a protected environment (with the IoTA to MQTTBroker traffic protected inside the internal network, and just the MQTT Broker globally accessible). So the connections have been kept insecure from the IoTA point of view. 

Provided that the Node.js client we use support SSL/TLS, I guess it should be really easy to modify the Agent to support that. But, for the reasons mentioned at the beginning of this comment, that particular feature it's not in the roadmap for the near future.

**Comment by perrolobo** [comment]
Yo diría que este pollo le interesa que el mqtt sea el seguro ¿no? O crees que habla de la comunicacion mqtt->iota?
