### ISSUE TITLE
delete service should return 204 instead 200

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-ul#174]
DEBUG >>>>>>>>>>>>>  Data sent:         >>>>>>>>>>>>> 
    > Comp: IOTA 
    > Method: delete 
    > Url: http://192.168.137.16:8086/iot/devices/di0120011tttx3 
    > Headers: {'Fiware-Service': u'1fi012001ttt', 'Fiware-ServicePath': '/subfi0120ttt', 'X-Auth-Token': '0e6985d6f2c94ff692745c348ef7b354'}
    > Params: {'protocol': 'IoTA-UL'} 
    > SENT REQUEST DATA SEEMS TO BE EMPTY 

DEBUG <<<<<<<<<<<<<<     Data responded:    <<<<<<<<<<<<<<
    < Response code: 204
    < Headers: {'X-Content-Type-Options': 'nosniff', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains;', 'Server': 'nginx', 'Fiware-Correlator': '6c05983b-065c-449d-b015-57c0721f3018', 'Connection': 'keep-alive', 'Date': 'Fri, 21 Oct 2016 11:08:15 GMT', 'X-Frame-Options': 'SAMEORIGIN'}
    < Empty Payload

**Comment by dmoranj** [comment]
This behavior belongs to the library, not to the particular IoTAgents. I'll clone this issue in the library.

**Comment by dmoranj** [comment]
Created [here](https://github.com/telefonicaid/iotagent-node-lib/issues/501)
