### ISSUE TITLE
Avoid empty spaces in md links

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/iotagent-ul#185]
[This is alink] (#alink)

should not be used.

Instead please use:

[This is alink](#alink)

the former is misunderstood by readthedocs and no link appears

**Comment by Keshav-NEC** [comment]
Hi @fgalan , I think these would be removed in previous documentation work. What's your opinion on this?

**Comment by fgalan** [comment]
I think the ongoing work on documentation re-working (issue https://github.com/telefonicaid/iotagent-node-lib/issues/1329) makes this issues obsolete. We are going to close it. @Keshav-NEC thanks for raising it!
