### ISSUE TITLE
Remove <a name> anchors

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/iotagent-ul#186]
they are actually not needed. use the automatic anchors created

## This is a title

anchor: #this-is-a-title

**Comment by jason-fox** [comment]
@dmoranj @dcalvoalonso  @fgalan 
This was fixed as part of #273  and should be closed

**Comment by fgalan** [comment]
For me is ok to close it but maybe @jmcanterafonseca (the original reporter of the issue) should do it.

**Comment by fgalan** [comment]
I think the ongoing work on documentation re-working (issue https://github.com/telefonicaid/iotagent-node-lib/issues/1329) makes this issues obsolete. We are going to close it. @Keshav-NEC thanks for raising it!
