### ISSUE TITLE
Use RabbitMQ as MQTT Broker

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/iotagent-ul#192]
Study the modifications that would be needed in the Agent for the use of RabbitMQ with the MQTT Plugin as MQTT Broker.

**Comment by AlvaroVega** [comment]
- [ ] acl topic plugin for rabbitmq was added to use AMQP binding.
- [ ] rabbitmq mqtt broker (MQTT bindig) has been tested (without acl) and works properly
