### ISSUE TITLE
Wrong error message when sending measures

### ISSUE THREAD

**Issue by gobaldia** [telefonicaid/iotagent-ul#199]
If I try to send a new measure as follows `http://localhost:7896/iot/d?i=A7&k=TEF&d=a|1|b|2|c|6|z|5` if `z` is not an attribute of device A7 I get the following error:
`404 Not Found`
`{
  "name": "DEVICE_NOT_FOUND",
  "message": "No device was found with id:A7"
}`

That's wrong, the error should be something as follows:
`400 Bad Request`
`{
  "name": "ATTRIBUTE_NOT_FOUND",
  "message": "Some of the attributes doesn't exist"
}`

**Comment by gobaldia** [comment]
Hi. Do you have any updates on this?

**Comment by Madhu-NEC** [comment]
Hi @gobaldia , @fgalan , @dmoranj 

As per my understanding, this issue is related to iotagent-node-lib as the log also states op=IoTAgentNGSI.NGSIService. Please find below screenshot for reference:

![attribute_error](https://user-images.githubusercontent.com/47887616/68451851-742f1480-0216-11ea-9365-552d8ec36660.PNG)

Please provide your opinion for the same.

**Comment by fgalan** [comment]
> Please provide your opinion for the same.

Maybe it's a good idea to repeat the test with a newer IOTA version. The issue was reported in February 2017 and the IOTA-UL and underlying iotagent-node-lib have quite evolved during thiese years.

**Comment by Madhu-NEC** [comment]
Hi @fgalan ,

I am able to reproduce the issue with the newer IOTA version. The logs are same as mentioned in previous screenshot but the logs are generated at [IOTA node-lib](https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/services/ngsi/ngsiService.js#L85) .

As per my opinion, PR for this issue should be raised on IOTA node-lib.

**Comment by fgalan** [comment]
> As per my opinion, PR for this issue should be raised on IOTA node-lib.

If you have identified the problema and can help solving it with a PR, please go ahead. We will have a look to it and provide feedback. If the solution is in the iotagent-node-lib repository, you are right, the PR should be done in that repository.

Thanks for have a look into this and your feedback and help!

**Comment by Madhu-NEC** [comment]
I have raised the [PR #827 ](https://github.com/telefonicaid/iotagent-node-lib/pull/827)for this issue at IOTAgent Node Lib.

**Comment by fgalan** [comment]
Could you provide the configuration (I guess, the content of the config.js file) used in the case shown in https://github.com/telefonicaid/iotagent-ul/issues/199#issuecomment-551393174, please? It will help to understand the case. Thanks!

**Comment by fgalan** [comment]
@Madhu-NEC I understand that after merging https://github.com/telefonicaid/iotagent-node-lib/pull/827 this issue can be closed. What do you think?

**Comment by Madhu-NEC** [comment]
Hi @fgalan ,
Yes, please close the issue.

**Comment by Chandradeep-NEC** [comment]
@fgalan 

Please assign this issue to @Madhu-NEC  as she has raised the PR which is merged now.

Thanks :)

**Comment by fgalan** [comment]
Done!
