### ISSUE TITLE
How integrate a Fiware Data model with the iotagent

### ISSUE THREAD

**Issue by dpellegrino** [telefonicaid/iotagent-ul#203]
Hi all,
I was wondering if there is an automatic/manual procedure, during the registration device phase, in order to create an entity from a Fiware Data Model (for example WasteContainer).
Thanks a best regards.
Dario

**Comment by Keshav-NEC** [comment]
Hey @dpellegrino, can you explain the issue briefly ? 
Hey @fgalan, what's your opinion on this ?

**Comment by fgalan** [comment]
I don't think Data Models are related with IOTAs. Or, with other words, you cannot assure a particular Data Model when you register a group/device at IOTA. It would entirely depend on which kind of information the device sends if it conforms or not to a particular Data Model.

Thus, I'm going to close this issue. However, in the case I'm wrong, please @dpellegrino elaborate on your idea and in the particular functionality you envision for IOTAs and of course we can reopen again the issue.
