### ISSUE TITLE
Incomplete DockerHub documentation

### ISSUE THREAD

**Issue by efviodo** [telefonicaid/iotagent-ul#204]
Can anyone fix the DockerHub[1] page related to the project? It does not explain very well how to do the deploy of the agent using Docker. In addition it has several broken links.

Best regards,
Emiliano

[1] https://hub.docker.com/r/fiware/iotagent-ul/

**Comment by AlvaroVega** [comment]
dockerhub page is just a copy from this repo. Please, use the original doc https://github.com/telefonicaid/iotagent-ul/blob/master/README.md
