### ISSUE TITLE
Starting at boot failed /etc/init.d/iotaul

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/iotagent-ul#214]
When an IOT agent start at boot, is failed because dependencies with iotamanager

When an IOT agent start, needs that the iotamanager be started
Then in /etc/init.d/iotaul

Need to change the line
```
# Required-Start: $local_fs $syslog $network
```
By
```
# Required-Start: $local_fs $syslog $network $iotamanager
```

We need to check this behaviour by development team

A note if we use monit to monitoring this services:
- Test with monit this behaviour

**Comment by Sunny-NEC** [comment]
@fgalan i want to work on this issue. Currently, I am trying with the patch mentioned in the issue by creating rpm file. Could you please elaborate on the second part i.e. test with monit?

**Comment by fgalan** [comment]
Not sure of the details... let's wait for @cesarjorgemartinez feedback (as author of the issue) about that

Maybe in the meanwhile you could do the PR with the firt part
