### ISSUE TITLE
Fix transport for an autoprovisioned device

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-ul#235]
Since transport is not set, default transport is always MQTT by conf.

i.e.:
```
curl -i -X GET 'http://localhost:7896/iot/d?k=rfz7xmuusvf9ikdv23wf7fmhv&i=disp25&d=|temperature|4&'
```
This is creating a device without transport defined, but we know that transport is HTTP

**Comment by fgalan** [comment]
Fixed by PR #236
