### ISSUE TITLE
Cannot modify value in entity

### ISSUE THREAD

**Issue by sickboy93** [telefonicaid/iotagent-ul#244]
I cannot modify value after device observation. These are my steps
I created an entity:
```
curl http://127.0.0.1:1026/v2/entities -s -S --header 'Content-Type: application/json' \
    -X POST -d @- <<EOF
{
  "id": "CoriLab",
  "type": "labs",
  "temperature": {
    "value": 23,
    "type": "int"
  }
}
EOF
```
Then the service
```
curl http://127.0.0.1:4061/iot/services -s -S --header 'Content-Type: application/json' --header 'Fiware-Service: serv2' --header 'Fiware-ServicePath: /' \
    -X POST -d @- <<EOF
    {
  "services": [
    {
      "apikey":   "labs",
      "cbroker":  "http://127.0.0.1:1026",
      "resource": "/iot/d",
      "entity_type": "labs"
    }
  ]
}
EOF
```
The device
```
curl http://127.0.0.1:4061/iot/services -s -S --header 'Content-Type: application/json' --header 'Fiware-Service: serv2' --header 'Fiware-ServicePath: /' \
    -X POST -d @- <<EOF
    {
  "services": [
    {
      "apikey":   "labs",
      "cbroker":  "http://127.0.0.1:1026",
      "resource": "/iot/d",
      "entity_type": "labs"
    }
  ]
}
EOF
```
And finally I sent the observation 
```
curl -X POST 'http://127.0.0.1:7896/iot/d?k=labs&i=26' -H 'Content-Type: text/plain' -d "t|25" -include
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 0
ETag: W/"0-2jmj7l5rSw0yVb/vlWAYkK/YBwk"
Date: Fri, 19 Jan 2018 15:28:16 GMT
Connection: keep-alive
```
But the value in the entity hasn't changed, what's wrong in my steps?

**Comment by fgalan** [comment]
You shouldn't create the entity directly at CB (first step in your report). I mean, the IOTA will create it for you at device provisioning time (step 3 in your report).

Could you repeat your test without creating the entity directly at CB after a clean reset? By clean reset I mean:

 1. Stop all processes (both IOTA and CB).
 2. Cleanup all the DBs (look for DBs starting with `orion` and `iot` in your Mongo shell)
 3. Start CB
 4. Start IOTAgent

**Comment by sickboy93** [comment]
I "solved" it, practically, since I created the instance directly at the CB, when I create the device it creates indeed another entity so it will not manage the entity created in the context broker. 

It's possibile manage the entity created in the CB with the device but it's necessary an header with the Fiware-Service in the POST for querying the entity.

Thank you for your help!

**Comment by fgalan** [comment]
Happy to know you have solved! :)
