### ISSUE TITLE
How to test that my Ultralight 2.0 IOT agent receives something

### ISSUE THREAD

**Issue by ktsakos** [telefonicaid/iotagent-ul#245]
Hello!

I am using the Ultralight 2.0 IDAS.
Although i can see that the payload, that my gateway sends,is subscribed at a specific topic into the mosquitto MQTT broker, how could i test that the IDAS is listening at port 4061 and that it is receiving something from the broker?

thanks a lot!

**Comment by fgalan** [comment]
IDAS is a bit confusing term, as it was used in the past to refer to a different pieces of sofware.

Just to be sure... when you say IDAS are you meaning the IOTAgent-UL which code is in the present repo (a Node.js program)? Or you refere to the old IDAS sofware?

**Comment by ktsakos** [comment]
I am refering to the IOTAgent-UL which is running  on a centos 7 vm as a service.I have access to it with rest calls and i also see that the payloads, that my gateway sends, are subscribed into the mqtt broker. How could i pass my payloads from the mosquitto to the iot agent and after to the context broker?

**Comment by fgalan** [comment]
This question should be addressed using StackOverflow http://stackoverflow.com. This way, all the Q&A about the FIWARE platform become available in a public and searchable knowledge base like StackOverflow, which is quite popular among developers.

In that sense, could you ask your question using that platform, please? Use the “fiware” tag. Once done, add the link to the question as new comment in this issue, then close the issue.

Thanks!

**Comment by ktsakos** [comment]
https://stackoverflow.com/questions/48464896/how-to-test-that-my-ultralight-2-0-iot-agent-receives-payload
