### ISSUE TITLE
IOTA-UL and MongoDB authentication

### ISSUE THREAD

**Issue by osfrance** [telefonicaid/iotagent-ul#252]
Hi, I would like to use ~~IdasUL~ IOTA-UL with MongoDB authentification, but I don't find any parameter in IdansUL documentation. 
It's an important problem for my organization because we must put IOT infrastructure in production and we can't use mongoDB without authentification mechanism. 
Thanks for reply.

**Comment by fgalan** [comment]
Not sure about the implementation status of this feature... Looking to iotagent-node-lib (used by iotagent-ul) maybe is a matter of adjust the mongoose connection parameters, more or less here:

https://github.com/telefonicaid/iotagent-node-lib/tree/master/lib/model/dbConn.js#L109

Please, keep us reported of your progress if you go into this direction :)

**Comment by TheNextLVL** [comment]
try to use in the `config.js`, inside the mongodb section the parameters `username` and `password` .
Example:

```
    mongodb: {
        host: 'mongodb',
        port: '27017',
        db: 'iotagentul'
        username: 'root'
        password: 'toor'
    },
```

**Comment by letavia** [comment]
Hola, I have tried the params as suggested by @TheNextLVL to no avail. I also found these two params in docker environment config: ADMIN_USER and ADMIN_PASSWORD. Are they used for mongodb authentication because they don't work. 

Another question is why the config.js is hard-coded if we are to use env variables in docker.

**Comment by TheNextLVL** [comment]
Hola letavia, try to put the username and password in the uri connection to the mongodb. Somthing like:
```
    mongodb: {
        host: 'username:password@host',
        port: '27017',
        db: 'iotagentul'
    },
```

**Comment by letavia** [comment]
I tried it but didnt work. Got this error message when I tried to access API /iot/services

> {"name":"INTERNAL_DB_ERROR","message":"An internal DB Error happened: MongoError: there are no users authenticated"}

Any other suggestions?

**Comment by letavia** [comment]
Finally succeeded by adding auth database param to the source code.
