### ISSUE TITLE
Review and rightly process TimeInstant

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-ul#263]
In a general case, UL agent receive measures like this one

```
2018-01-01T00:00:00|t|2|r|3#2018-01-02T00:00:00|t|1|r|4
```

On progressing _each_ measure to the CB the behaviour should be as follows:

*  Timestamp should be use as `TimeInstant` _metadata_ in the attributes included in the  measure, e.g. the attributes mapped to `t` and `r` in this case.
*  Timestamp should be use as `TimeInstant` _attribute_ in the entity corresponding to the device.

Check if the current behaviour is this one (it seems is not) and change if needed

**Comment by manucarrace** [comment]
The key issue is to be able to save the adquisition time of every attribute.

**Comment by fgalan** [comment]
> The key issue is to be able to save the adquisition time of every attribute.

Yes. It is supposed the `2018-01-01T00:00:00` and `2018-01-02T00:00:00` mean adquisition times at the device (although at the end is up to what the device wants to put there ;))

**Comment by fgalan** [comment]
This issue has been created in the IOTA-UL repository given that the requirement has come bottom-up after analysing the UL payload. However, it could be solved in the iotagent-node-lib space (an issue should be created in that repo in that case) and be solved in general for all agents.

**Comment by fgalan** [comment]
"Parallel" issue in JSON repo: https://github.com/telefonicaid/iotagent-json/issues/289

**Comment by manucarrace** [comment]
I've performed some tests.

Case 1:
2018-01-01T00:00:00|t|2|r|3#2018-01-02T00:00:00|t|1|r|4
Looking at the entity
TimeInstant=2018-01-02T00:00:00
t=1, TimeInstant_md=2018-01-02T00:00:00
r=3, TimeInstant_md=2018-01-02T00:00:00

Case 2:
2018-01-01T00:00:00|t|2|r|3#2018-01-02T00:00:00|t|1|d|4
Looking at the entity
TimeInstant=2018-01-02T00:00:00
t=1, TimeInstant_md=2018-01-02T00:00:00
r=3, TimeInstant_md=2018-01-01T00:00:00
d=4, TimeInstant_md=2018-01-02T00:00:00

Case 3:
t|2|r|3#2018-01-02T00:00:00|t|1|d|4
Looking at the entity
TimeInstant=2018-01-02T00:00:00
t=1, TimeInstant_md=2018-01-02T00:00:00
r=3, TimeInstant_md=<Current Time>
d=4, TimeInstant_md=2018-01-02T00:00:00

Case 4:
2018-01-01T00:00:00|t|2|r|3#t|1|d|4
Looking at the entity
TimeInstant=<Current Time>
t=1, TimeInstant_md=<Current Time>
r=3, TimeInstant_md=2018-01-01T00:00:00
d=4, TimeInstant_md=<Current Time>

For me the behaviour is as expected.
