### ISSUE TITLE
amqp configuration is not supported

### ISSUE THREAD

**Issue by chicco785** [telefonicaid/iotagent-ul#268]
1. host is hardcoded
1. user and password are not supported

ect

**Comment by fgalan** [comment]
How about the AMQP support in iotagent-json? Does it has the same issues? (in order to create a "parallel" issue in its repository in that case).

**Comment by chicco785** [comment]
same issue (and most probably code won't change much) i also actually spotted few other hardcoding issues, like for example the protocol string 'MQTT' while looking for a device, and the default resource while looking for device group ...

**Comment by fgalan** [comment]
Thus, I have created a "twin" issue in IOTA JSON repo at https://github.com/telefonicaid/iotagent-json/issues/297
