### ISSUE TITLE
NGSIv2 autocast not working fro Float and Integer

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-ul#271]
IOTA-UL running in NGSIv2 mode with autocast:

```
$ sudo cat /proc/$IOTA_UL_PID/environ | tr '\0' '\n' | grep IOTA
...
IOTA_AUTOCAST=true
IOTA_CB_NGSI_VERSION=v2
...
```

Given the following service in place:

```
	{
		"services": [
			{
				"_id": "5b2cff8823dc8c60429221b8",
				"__v": 0,
				"iotagent": "http://10.0.0.2:4061",
				"apikey": "o111njgfl1ai8lqkt9lpzxaaa",
				"entity_type": "device",
				"service_path": "/ssa",
				"service": "s1",
				"resource": "/iot/d",
				"description": "IoTAgent Ultralight 2.0 - Node.js",
				"protocol": "IoTA-UL",
				"internal_attributes": [],
				"attributes": [],
				"lazy": [],
				"static_attributes": [],
				"commands": []
			}
		],
		"count": 1
	}	
```

Creating a device with:

```
	POST /iot/devices

	{
	  "devices": [
		{
		  "device_id": "dev2ul", 
		  "entity_name": "entity2ul", 
		  "entity_type": "device",
		  "attributes": [
			{ "object_id": "w", "name": "power", "type": "Integer" },
			{ "object_id": "e", "name": "electricPotential", "type": "Float" },
			{ "object_id": "p", "name": "presence", "type": "Boolean" },
			{ "object_id": "n", "name": "nonsense", "type": "None" }
		  ],
		  "endpoint": "http://foo.bar:999",
		  "protocol": "IoTA-UL"
		}
	  ]
	}
```

Sending measures with:

```
GET /iot/d?i=dev2ul&k=o111njgfl1ai8lqkt9lpzxaaa&d=w|42|e|23.24|p|true|s|on|n|null
```

Getting the entity:

```
	GET https://{{host}}:10027/v2/entities/entity2ul
	
	{
		"id": "entity2ul",
		"type": "device",
		"TimeInstant": {
			"type": "DateTime",
			"value": "2018-07-06T12:06:47.00Z",
			"metadata": {}
		},
		"electricPotential": {
			"type": "Float",
			"value": "23.24",
			"metadata": {
				"TimeInstant": {
					"type": "DateTime",
					"value": "2018-07-06T12:06:47.00Z"
				}
			}
		},
		"nonsense": {
			"type": "None",
			"value": null,
			"metadata": {
				"TimeInstant": {
					"type": "DateTime",
					"value": "2018-07-06T12:06:47.00Z"
				}
			}
		},
		"power": {
			"type": "Integer",
			"value": "42",
			"metadata": {
				"TimeInstant": {
					"type": "DateTime",
					"value": "2018-07-06T12:06:47.00Z"
				}
			}
		},
		"presence": {
			"type": "Boolean",
			"value": true,
			"metadata": {
				"TimeInstant": {
					"type": "DateTime",
					"value": "2018-07-06T12:06:47.00Z"
				}
			}
		},
		"s": {
			"type": "string",
			"value": "on",
			"metadata": {
				"TimeInstant": {
					"type": "DateTime",
					"value": "2018-07-06T12:06:47.00Z"
				}
			}
		}
	}
```

**Problem:** autocast is not working for Float and Integer types. However it is working for Boolean an None case. It is a bit weird... I have expected a all-of-nothing behaviour in the case of error.

I'll continue debugging on this, but it would be great if somebody could confirm the problem reproducing it in another environment. What do you think @dcalvoalonso ? Does this issue makes any sense to you? (I don't know but it could be due to something wrong on my testing environment...)

**Comment by dcalvoalonso** [comment]
@fgalan, for device provision use:

```
	{
	  "devices": [
		{
		  "device_id": "dev2ul", 
		  "entity_name": "entity2ul", 
		  "entity_type": "device",
		  "attributes": [
			{ "object_id": "w", "name": "power", "type": "**Number**" },
			{ "object_id": "e", "name": "electricPotential", "type": "**Number**" },
			{ "object_id": "p", "name": "presence", "type": "Boolean" },
			{ "object_id": "n", "name": "nonsense", "type": "None" }
		  ],
		  "endpoint": "http://foo.bar:999",
		  "protocol": "IoTA-UL"
		}
	  ]
	}
```

As you can see in https://www.w3schools.com/js/js_json_datatypes.asp, JSON native type for Integer or Floats is Number. This is also reflected in `Partial Representations` section of http://telefonicaid.github.io/fiware-orion/api/v2/stable/:

> If value is a number, then type Number is used.

**Comment by fgalan** [comment]
Thanks for the clarifications. I think I missunderstood it due to I see [this code](https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/plugins/expressionParser.js#L172), which cast based on "Integer" and "Floats" but now I see that it only applies to expression plugin. Is my interpretation correct?

I'm trying to find the part of the code that does the autocast based en "Number" type, but I'm unable to find it (search https://github.com/telefonicaid/iotagent-ul/search?q=autocast&unscoped_q=autocast and https://github.com/telefonicaid/iotagent-node-lib/search?q=autocast&unscoped_q=autocastdoesn't provide relevant results). Could you point to the right point, please?

**Comment by dcalvoalonso** [comment]
You're right, that part only applies to expression plugin...I understand that it confused you. Maybe we should study if it is possible to align https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/plugins/expressionParser.js#L172 so that `Number` type is used?

Autocast functionality is implemented at https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/services/ngsi/ngsiService.js#441

**Comment by fgalan** [comment]
Yes, I think we should align to use the same pattern and that pattern should be the one based on Number (as it is the one more aligned with NGSIv2 way of working). In fact, it is a pity not having detected this when the NGSIv2 active attributes functionality was developed... but it was a complex work so it's normal this details was missed :)

I can create an issue about it.

**Comment by fgalan** [comment]
Issue created at https://github.com/telefonicaid/iotagent-node-lib/issues/643. I'm closing this one.
