### ISSUE TITLE
Configure "timeinstant" metadata per group/device instead of global iota config

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/iotagent-ul#291]
Now (config.js )"timestamp: true" establish a common politic for the whole Agent It should be particular to each group/device

**Comment by mrutid** [comment]
Moved to Iotagent node_lib

**Comment by fgalan** [comment]
Moved to https://github.com/telefonicaid/iotagent-node-lib/issues/655. Closing in this repo.
