### ISSUE TITLE
Remove Node v4

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-ul#303]
(To be addresses in January 2019)

Node v4 will be removed by the end of 2018. In particular, this issue involves the following actions:

* Node v4 should be removed from .travis.yml
* engine version should be modified to be >=6 in packages.json
* logops library should be updated to 2.1.0 in packages.json

**Comment by Jagatjot** [comment]
hi @fgalan the tests again failed in this can u please relaunch the test to solve the issue.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-ul/pull/315

I'll relaunch the tests.
