### ISSUE TITLE
Wrong mirror webhook config

### ISSUE THREAD

**Issue by caa06d9c** [telefonicaid/iotagent-ul#316]
Please, change the mirror webhook config as described [here](https://fiware-requirements.readthedocs.io/en/latest/repo_webhook/index.html)

**Comment by fgalan** [comment]
Updated. Now it looks like:

![imagen](https://user-images.githubusercontent.com/1534240/49799878-5c20ed80-fd46-11e8-98fe-eff34d5dc568.png)

Please check it and close the issue if it is working fine. Thx!

**Comment by caa06d9c** [comment]
Checked. Thanks!
