### ISSUE TITLE
Wrong error 404 when sending data with timestamp

### ISSUE THREAD

**Issue by flusflas** [telefonicaid/iotagent-ul#322]
When updating an entity specifying a timestamp, the entity is correctly updated but I get the following error message with code 404:

Request:
```
POST /iot/d?k=4jggokgpepnvsb2uv4s40d59ov&amp; i=device4573 HTTP/1.1
Host: localhost:7896
Content-Type: text/plain
cache-control: no-cache
2016-06-13T00:35:33Z|l|38.127,-1.987|a|43|s|120|h|270
```

Response:
```
{
   "name": "DEVICE_NOT_FOUND",
   "message": "No device was found with id:urn:ngsi-ld:Device:4573"
}
```

Thus, I cannot be certain of the process success. Not specifying timestamp gives a response with status code 200.

**Comment by fgalan** [comment]
The URL is a bit weird with &amp and space after it:

```
POST /iot/d?k=4jggokgpepnvsb2uv4s40d59ov&amp; i=device4573
```

Typical ones are like that:

```
POST /iot/d?k=4jggokgpepnvsb2uv4s40d59ov&i=device4573
```

Not sure, but may be related with the problem...

**Comment by sysseon** [comment]
Hi Fermín, sorry for the delay in replying.

The URL has no &amp, it is just the way Postman gives requests representation. The URL is

`http://localhost:7896/iot/d?k=4jggokgpepnvsb2uv4s40d59ov&i=device4573.`

I have tested it with several device names and the error is the same (is not really an error, as the data is correctly inserted, but when specifying a timestamp in UL a response error is returned).

As for your second reply, I've done the same test with the same result. Now, the response is correct. Also, a problem I had when sending multiple measurements in the same UltraLight message (with '#') with different timestamps is gone, and now the timestamp is correct for every group of attributes. Therefore, the solution was to enable NGSIv2 in the IoT Agent.

Is there any Docker image available with this configuration or I should continue building it myself?

Thanks!

**Comment by fgalan** [comment]
Thus, I'd suggest to close the issue and if it comes again the same problem, then re-open a new fresher one. What do you think?
