### ISSUE TITLE
Log always writes the same correlator and transaction id

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/iotagent-ul#326]
IotAgent log file always writes the same correlator and transaction id for every transaction. Even more, the service and the subservice is always the same. 

The same problem affects both UL and JSON IoTAgents.

Looking at the log file you can see always the same values of corr, trans, srv and subsrv.

time=2019-01-16T16:48:55.672Z | lvl=DEBUG | corr=321e0df3-60e7-4d1b-95f4-4f7c29a30a47 | trans=321e0df3-60e7-4d1b-95f4-4f7c29a30a47 | op=IoTAgentNGSI.NGSIService | srv=badajozesmas | subsrv=/Estacion_Meteorologica | msg=Received the following response from the CB: Value updated successfully
...
time=2019-01-16T16:52:50.435Z | lvl=DEBUG | corr=321e0df3-60e7-4d1b-95f4-4f7c29a30a47 | trans=321e0df3-60e7-4d1b-95f4-4f7c29a30a47 | op=IoTAgentNGSI.NGSIService | srv=badajozesmas | subsrv=/Estacion_Meteorologica | msg=Updating device value in the Context Broker at [http://10.0.0.2:1026/v2/entities/AV_MEDVO_CA_0001/attrs] | comp=IoTAgent

Correlator and transaction id changes after restart, but it remains always the same for every transaction.

**Comment by fgalan** [comment]
(Actually this is a per-agent issue, so it has been transferred)

**Comment by DeepshikhaNEC** [comment]
@fgalan  Hi, I have fixed this issue #326 and also PR has been raised. 

Request you to please confirm the same and if the PR is ok then please merge it in master branch.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-ul/pull/428 (and https://github.com/telefonicaid/iotagent-node-lib/pull/864)
