### ISSUE TITLE
[SHOULD] Repo description, topics and URL link

### ISSUE THREAD

**Issue by jason-fox** [telefonicaid/iotagent-ul#332]
Please click the edit button at the head of the repo and amend the description link and topics as shown (or similar):

### Link

> https://fiware-iotagent-ul.rtfd.io/

### Topics

`fiware`, `iot`, `iot-agent`

- SHOULD requirement from the TSC.

**Comment by fgalan** [comment]
Done!

Please have a look and close this issue if you find it solved.
