### ISSUE TITLE
 iotagent-ul 2.0 supports MQTT Secure TLS 1.2

### ISSUE THREAD

**Issue by lprunella** [telefonicaid/iotagent-ul#354]
Hi, we have mqtt device that send observation with TLS 1.2 encryption protocol. We would like to send these observations to an instance of iot-agent ultralight 2.0 that is installed on the cloud with an instance of Orion Context Broker.
How we can do that?
We know that in the recent past this feature weren't in the roadmap, is in the meantime changing something?
Thank you

**Comment by fgalan** [comment]
Support to secure MQTTS has not been developed for this IOTA yet, but I think that @aarranz (which develop it for IOTA-JSON, see https://github.com/telefonicaid/iotagent-json/pull/372) is on it.

Maybe @aarranz could provide more information about the status of the implementation.

**Comment by aarranz** [comment]
Hi @lprunella, hi @fgalan,

It should be easy to port mqtts support from iotagent-json, but I'm going to be a bit busy this week. I'll try to provide some feedback about whether I can work on it or not as soon as possible.

Best regards,
Álvaro

**Comment by fgalan** [comment]
@lprunella if this urges, then maybe you could mimic the changes that @aarranz did in telefonicaid/iotagent-json#372 in this agent and create a pull request with it. The @aarranz could review that pull requests. Makes sense?

**Comment by lprunella** [comment]
Hi @aarranz <https://github.com/aarranz>, hi @fgalan 
<https://github.com/fgalan>,

we have a project that will start on the first week of june and this 
project will utilize our mqtt gateway (https://www.beeta.it/en/) with 
tls 1.2. If you think that the new ultralight 2.0 agent with tls support 
will draw up respect ( more or less ) this time we can use it otherwise 
we must to use Mosquitto broker.

We hope so much to make this project "Fiware compliant" using in such a 
way your agent and your Context Broker

Thank you


Il 28/05/19 09:50, Fermín Galán Márquez ha scritto:

**Comment by fgalan** [comment]
If you are in a rush, what about using the IOTA-JSON agent in your project? That one supports in theory secure MQTT.

**Comment by lprunella** [comment]
OK, i take a look to this IOTA-JSON agent.

In our scenario there is a client ( our gataway ) and a server with a 
context broker ( until now mosquitto)

For tls the configuration parameters on server side are:

listener 8883
tls_version tlsv1.2
cafile /etc/mosquitto/conf.d/ca.crt
certfile /etc/mosquitto/conf.d/server.crt
keyfile /etc/mosquitto/conf.d/server.key
require_certificate false

while for client side:

#Bridge
connection beetabox
address 192.168.1.201:8883
bridge_tls_version tlsv1.2
clientid A00001158
username admin
password secretpass
notifications false
start_type automatic
bridge_cafile /etc/mosquitto/conf.d/ca.crt--------------
bridge_insecure true
cleansession false

Now i think to use your docker-compose configuration 
(Rif.https://github.com/telefonicaid/iotagent-json/tree/master/docker

) at my new server side and maybe i have to add the environment variable 
about IOTA_MQTT_

Is this roadmap correct?

Thank you

Best regards

Nicola



Il 28/05/19 16:54, Fermín Galán Márquez ha scritto:

**Comment by StWiemann** [comment]
I would also really appreciate if the iotagent-ul would work with mqtt brokers using tls encryption.

**Comment by tstorek** [comment]
Hello,
any news on this @aarranz?  We used iota json already for this purpose and it works well. Hence, the same functions may also work for ul. We tried it once with ul and it worked but that was quite a while ago with an old version. Maybe I can double check beginning of next year.

**Comment by SBlechmann** [comment]
Hey there,

anything new for the UL agent @aarranz?

**Comment by fgalan** [comment]
MQTTS support finally implemented by PR https://github.com/telefonicaid/iotagent-ul/pull/422 thanks to @jason-fox
