### ISSUE TITLE
Commands over mqtt are missing "value"

### ISSUE THREAD

**Issue by StWiemann** [telefonicaid/iotagent-ul#357]
Hi there I am using Orion-ld, iot-agent-UL and MQTT to receive and send data. I would like to send a command with a specific value instead of only a commandname like in the tutorial (open, close, lock, etc.).
I followed the tutorial steps, provisioned a device with:

```
{
   "devices": [
     {
       "device_id":   "urn:ngsi-ld:pysense:002",
       ...
       "attributes": [
         { "object_id": "gi", "name": "gatewayID", "type": "Text" },
         ...
       ]
       "commands": [
 	  {"name": "color", "type": "command", "value": ""},
 	  {"name": "brightness", "type": "command", "value": ""}
 	  ]
     }
   ]
  }
```
then I setup my registrations for those commands and GET /v2/registrations/ gets me: 

```
[
    {
        "id": "5cf4dee02c20d186dbc98832",
        "description": "Setting LED",
        "dataProvided": {
            "entities": [
                {
                    "id": "urn:ngsi-ld:pysense:002",
                    "type": "pysense"
                }
            ],
            "attrs": [
                "color",
                "brightness"
            ]
        },
        "provider": {
            "http": {
                "url": "http://orion:1026/v1"
            },
            "supportedForwardingMode": "all",
            "legacyForwarding": true
        },
        "status": "active"
    }
]
```
if I send a command like below to "**/v2/entities/urn:ngsi-ld:pysense:002/attrs**", I only get a "**urn:ngsi-ld:pysense:002@color|**" on my mqtt-broker. The value is missing. Did I miss something or is this a bug? 

```
{
  "color": {
      "type" : "command",
      "value" : "100"
  }
}
```
I would really appreciate some help. 
Thank you!

**EDIT:**
I found a workaround for this problem. It works for me to register the command as follows: 

```
curl -iX POST \
  'http://localhost:1026/v2/registrations' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
  "description": "Setting LED",
  "dataProvided": {
    "entities": [
      {
        "id": "urn:ngsi-ld:pysense:002", "type": "pysense"
      }
    ],
    "attrs": ["color", "brightness"]
  },
  "provider": {
    **"http": {"url": "http://iotagent:4041"},**
    "legacyForwarding": true
  }
}'
```
and instead of the v2 patch method to issue commands the v1 directly with orion works: 

```
curl -iX POST \
  'http://localhost:1026/v1/updateContext' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
    "contextElements": [
        {
            "type": "pysense",
            "isPattern": "false",
            "id": "urn:ngsi-ld:pysense:002",
            "attributes": [
                {
                    "name": "color",
                    "type": "command",
                    "value": "25"
                }
            ]
        }
    ],
    "updateAction": "UPDATE"
}'
```

**Comment by fgalan** [comment]
It seem to be very similar to the case described in https://stackoverflow.com/questions/56427851/fiware-iot-agent-ul-send-command-value-via-mqtt-to-device, doesn't it?

In that case, I'd suggest to close this issue (editing the question in SOF if some important piece of information here has not been included there) and continue discussion in SOF. Although it isn't a written rule, SOF is more for doubts and general support, github issues are more for problems/bugs/enhancements identified in the software. In this case, I think SOF is more appropriate.

Thanks!

**Comment by StWiemann** [comment]
It is similiar, because it is my question there. Since I didn't get any reaction there I came here, because for me this is a pressing issue and as far as I understand this is the piece of software in question. 

I do get that this might be a little tedious for you and that this might not be the ideal place to ask questions about basic functionalities, but you would really help me out if you could tell me, whether the value of "color" should actually be part of the mqtt payload and the fault is with my setup resp. the tutorial or if this is a bug. Did this actually ever work for anyone? Information on that is incoherent and scarce (for example which method is actually the up-to-date method to issue commands etc.)
