### ISSUE TITLE
Agent keeps crashing

### ISSUE THREAD

**Issue by jmezzera** [telefonicaid/iotagent-ul#360]
Hi,
I'm currently using the agent together with mosquitto and, obviously, Orion CB. Yesterday, I noticed that Orion was not receiving data from entities that used MQTT + UL and digging a little bit deeper I found that the problem was that the agent process had stopped. Unfortunately, I restarted the service (I'm using nohup to keep the service alive) and thus overrode the log file.
Today, the agent worked for a few hours and then crashed again. This time, I took a look at the log and the last entry was a successful measurement (`Multiple measures for device [...] with apiKey [...] successfully updated`); so, apparently, there were no -detected- runtime errors.

Is there any known issue that could be causing this problems?

Thanks in advance

**Comment by fgalan** [comment]
Just to know a little bit about your usage environment:

* Which IOTA version are you using?
* Which Orion version are you using?
* How are IOTA and Orion deployed? Using docker or not?
* The failing pattern is always the same (I mean, the last log line before the crash is always the one `Multiple measures for device [...] with apiKey [...] successfully updated` you cite)?
* Is any relevant trace at kernel level about this issue (sometimes kernel kills processes if they are taking too many resources or whichever problem and that leaves a trace in the kernel logs)?

**Comment by jmezzera** [comment]
Thank you for your response. My apologies for the lack of environment information.
This is my environment (as presented by each components API)

- IOTA-UL:
`{
    "libVersion": "2.9.0-next",
    "port": 4061,
    "baseRoot": "/",
    "version": "1.9.0-next"
}`
- Orion:
`
{
    "orion": {
        "version": "1.7.0-next",
        "uptime": "76 d, 22 h, 26 m, 4 s",
        [...]
    }
}
`

Orion is deployed as a docker (Docker image fiware/orion, tag latest, ID 99b8cdc786eb).
The IOTA is running on the OS (Ubuntu 16.04).

As I commented in the original post, the first time this happened, I overrode the log file. The second, and last time it crashed, the log ended with the line I mentioned. It didn't happen again.

As you recommended, I dug a little bit in the system logs and I found that a node service was killed due to lack of memory. However, is there any way to know for sure that the given PID by `dmesg` corresponds with the IOTA process that crashed?

**Comment by fgalan** [comment]
> However, is there any way to know for sure that the given PID by dmesg corresponds with the IOTA process that crashed?

I don't know, but maybe google does :) However, how many node processes do you run in your OS? If you only run the IOTA node process (or if you run many node processes but all the other ones are up and running) then, by elimination, the one killed by the kernel is that one.

**Comment by fgalan** [comment]
>  The IOTA is running on the OS (Ubuntu 16.04).

Which node version are you using to run the IOTA?

**Comment by jmezzera** [comment]
> Which node version are you using to run the IOTA?

I'm running version v10.15.3.

**Comment by jmezzera** [comment]
> I don't know, but maybe google does :)
I searched for a while but did not find anything useful. I even asked a coworker who has advanced Linux experience but we could not find any information. This might make sense having in mind that the process died yesterday.

> However, how many node processes do you run in your OS? If you only run the IOTA node process (or if you run many node processes but all the other ones are up and running) then, by elimination, the one killed by the kernel is that one.

You made a good point here. In this moment I only have two of them (IOTA-json and IOTA-ul) in this VM. Since the other agent did not die, this may be a pretty good candidate.

**Comment by fgalan** [comment]
It would be great to have some way of reproducing the problem in a deterministic way. However, I understand it is not possible, so I can only provide some hints:

* Try to use some other Node version (v8 or v12) in order to check if the issue also happens there
* If happens there, look to the logs to check if the last trace is the same you saw, so we can now if the "crashing point" is always the same
* Put this in "quarantine". If you don't see happening again in a while, then maybe the crash was due to some kind of unrelated problem due to the execution environment (node interpreter, SO, etc.).

**Comment by jmezzera** [comment]
Ok, I will monitor it closely in the next days. For now I'm closing this issue and in case it happens again, I will reopen it. Ok?
Thank you for all these advices

**Comment by tstorek** [comment]
Hello, 
I think I might have the same issue:
My Agent (Node 8.16) always stops working with the beginning of a new week. I thought it would be my MQTT-Broker. Is it correct, that the Agents does auto-reconnect? 


I am not very familiar with node.js but I understand the function in the mqtt binding like this: 
As I understand the keepalive option is disabled. Hence the connection stays open all the time. The timeout for establishing the connection is the connectTimeout in ms. Why is it set to 1 hour?

Where does the reconnect take place after the broker was maybe restarted. I found this issue in the json-implementation as well. 


`function start(callback) {
    var options = {
        keepalive: 0,
        connectTimeout: 60 * 60 * 1000
    };

    config.getLogger().info(context, 'Starting MQTT binding');

    if (config.getConfig().mqtt && config.getConfig().mqtt.username && config.getConfig().mqtt.password) {
        options.username = config.getConfig().mqtt.username;
        options.password = config.getConfig().mqtt.password;
    }

    mqttClient = mqtt.connect(
        'mqtt://' + config.getConfig().mqtt.host + ':' + config.getConfig().mqtt.port,
        options
    );
    mqttClient.on('error', function(e) {
        /*jshint quotmark: double */
        config.getLogger().fatal("GLOBAL-002: Couldn't connect with MQTT broker: %j", e);
        /*jshint quotmark: single */
        callback(e);
    });

    mqttClient.on('message', commonBindings.mqttMessageHandler);

    mqttClient.on('connect', function(ack) {
        config.getLogger().info(context, 'MQTT Client connected');
        recreateSubscriptions(callback);
    });
}`

Do you think updating the node version might help? I forget to check the log before I restarted, but I can add it next week, after the next crash.

Thanks,

Thomas

**Comment by tstorek** [comment]
Maybe we can reopen this issue or is it better have a new one?

**Comment by fgalan** [comment]
I'd suggest opening a new refresh issue (with a reference to this one, as potentially related one). Thanks!
