### ISSUE TITLE
Configuration Retrieval not supported in IoTAgent-UL MQTT binding?

### ISSUE THREAD

**Issue by mgaggero** [telefonicaid/iotagent-ul#361]
Hi,
    it seems configuration retrieval is not supported in IoTAgent-UL MQTT binding. Looking at the documentation there are no references and in the code, file _iotagent-ul/lib/bindings/MQTTBinding.js_, 

```
function generateTopics(callback) {
    var topics = [];

    config.getLogger().debug(context, 'Generating topics');
    topics.push('/+/+/' + constants.MEASURES_SUFIX + '/+');
    topics.push('/+/+/' + constants.MEASURES_SUFIX);
    //topics.push('/+/+/' + constants.CONFIGURATION_SUFIX + '/' + constants.CONFIGURATION_COMMAND_SUFIX);
    topics.push('/+/+/' + constants.CONFIGURATION_COMMAND_UPDATE);

    callback(null, topics);
}
```
the topic for configuration retrieval is commented.

Looking at the file history, that piece of code has been commented in commit 6b834bc8de3c2b0d45cc21a2102a0455fda28488 but I could not find any information about. 

Massimo.

**Comment by AlvaroVega** [comment]
https://github.com/telefonicaid/iotagent-ul/pull/362

**Comment by mgaggero** [comment]
Okay, so it's a design choice? I'm currently working on a Pull Request to provide this functionality to the IoTAgent-UL for the MQTT transport. I think it can be useful for resource constrained devices using UL-2 to periodically retrieve configurations like polling intervals, endpoints and so on...

**Comment by fgalan** [comment]
I think is not a design choice, but a gap in the functionality. Looking to the description of the functionality in the JSON agent:

* https://github.com/telefonicaid/iotagent-json/blob/master/docs/usermanual.md#configuration-retrieval (JSON and HTTP transport)
* https://github.com/telefonicaid/iotagent-json/blob/master/docs/usermanual.md#configuration-retrieval-1 (JSON and MQTT transport)

I understand that the same functionality could be developed for UL. The only difference would be the transport payload.

Thus it would be great to have a pull request implementing this gap in IOTA UL :) Don't forget to include documentation (copy-pasting from the above links could help) and unit test to cover it and ensure nothing previously existing breaks.

Thanks!

**Comment by mgaggero** [comment]
Hi,
    I just opened a pull request (#364) that provides Configuration Retrieval for the MQTT binding. At the moment, only the 'configuration' command type is supported.
I updated the documentation with the new feature and I have added some rows for the testing environment in README.md.

**Comment by fgalan** [comment]
> At the moment, only the 'configuration' command type is supported

Is the same level of support that IOTA-JSON currently has?

**Comment by mgaggero** [comment]
My PR for IOTA-UL only supports the basic configuration retrieval mechanism (polling mode) while IOTA-JSON also supports the  'subscription' configuration retrieval mechanism. 
The basic configuration retrieval mechanism works in the same way in my PR and IOTA-JSON, differing only in the message format.
You mean this for same level?

**Comment by fgalan** [comment]
Yes. Thanks for the clarifications!

**Comment by fgalan** [comment]
PR #364 has been merged, but I understand this issue will keep opened while the functionality is completed (the new PR you mention in https://github.com/telefonicaid/iotagent-ul/pull/364#discussion_r298564821 is to come).

**Comment by mgaggero** [comment]
Ok, I think is just matter of days.

**Comment by mgaggero** [comment]
Ok, I was wrong. Found the problem in the tests, the 'subscription' mechanism is ready.

**Comment by fgalan** [comment]
I understand that PR https://github.com/telefonicaid/iotagent-ul/pull/365 completes this issue.

Is anything pending or this issue could be closed?

**Comment by mgaggero** [comment]
For me there is nothing pending with this issue. It can be closed.

Thank you!
