### ISSUE TITLE
In mqtt set default keepalive parameter to default mqtt software value 60 seconds

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/iotagent-ul#370]
In mqtt set default keepalive parameter to default mqtt software value 60 seconds

See: https://www.npmjs.com/package/mqtt or https://github.com/mqttjs/MQTT.js#connect

**Comment by AlvaroVega** [comment]
twin issue https://github.com/telefonicaid/iotagent-json/issues/413

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/iotagent-ul/pull/461
