### ISSUE TITLE
Selectively ignore some measures

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-ul#372]
Support selective ignore of measures so the IOTA doesn't progress for instance the measure on `m` when it receives `n|044.7|m|30`.

**Comment by fgalan** [comment]
Twin issue in IOTA-JSON: https://github.com/telefonicaid/iotagent-json/issues/416

**Comment by Chandradeep-NEC** [comment]
@fgalan 
We have started working on this issue. Sorry for the delay.

**Comment by Chandradeep-NEC** [comment]
@fgalan 
Thanks for your review.
I request you to please assign this issue to @DeepshikhaNEC

**Comment by fgalan** [comment]
Assigned to @DeepshikhaNEC

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-ul/pull/430 (and https://github.com/telefonicaid/iotagent-node-lib/pull/873)
