### ISSUE TITLE
Strictly following documentation ./create-rpm.sh doesn't work

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/iotagent-ul#45]
Trying to create rpm package as described in documentation I get:

```
[root@foobar rpm]# ./create-rpm.sh 1.0.0 1
A product version must be specified with -v parameter.

usage: create-rpm.sh [options] 

Options:

    -h                    show usage
    -v VERSION            Mandatory parameter. Version for rpm product preferably in format x.y.z 
    -r RELEASE            Mandatory parameter. Release for product. I.E. 0.ge58dffa 
``` 
However, if I use

```
[root@foobar rpm]# ./create-rpm.sh -v 1.0.0 -r 1
```

All works ok.

Not sure if the bug is in the doc or in the script :) Actually, I prefer using -v and -r better than positional parameters.

**Comment by dmoranj** [comment]
Damn it! The syntax in the documentation belongs to the previous version of the script. I'll change it for the next version.

**Comment by fgalan** [comment]
Maybe this problem is affecting to more repositories?

**Comment by dmoranj** [comment]
Maybe. We need to check all our documentation carefully, as we have been adding lots of features and fixing bugs without taking enough care of it.

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/iotagent-ul/pull/50
