### ISSUE TITLE
Docker Secrets partially broken

### ISSUE THREAD

**Issue by TrueSkrillor** [telefonicaid/iotagent-ul#473]
According to the documentation of the docker image, the following environment variables can be passed as a docker secret by appending `_FILE` at the end of the environment variable:
- `IOTA_AUTH_USER`
- `IOTA_AUTH_PASSWORD`
- `IOTA_AUTH_CLIENT_ID`
- `IOTA_AUTH_CLIENT_SECRET`
- `IOTA_MONGO_USER`
- `IOTA_MONGO_PASSWORD`
- `IOTA_MQTT_KEY`
- `IOTA_MQTT_USERNAME`
- `IOTA_MQTT_PASSWORD`
- `IOTA_AMQP_USERNAME`
- `IOTA_AMQP_PASSWORD`

The docker secrets functionality for the first six variables (AUTH and MONGO) is implemented within the underlying iotagent-node-lib and works properly. However, the docker secrets functionality for the MQTT and AMQP variables is broken due to the following commit:

https://github.com/telefonicaid/iotagent-ul/commit/6938d883bbb539dd24e267504bf102f4d11b06ae

Handling the docker secrets for the MQTT and AMQP variables has been dropped without removing the variables from the related part of the documentation or implementing an approach similar to the one present within iotagent-node-lib.

**Comment by fgalan** [comment]
Maybe @jason-fox (author of that commit) could provide feedback on this (and/or provide the fix, if needed).

**Comment by fgalan** [comment]
After merging PR https://github.com/telefonicaid/iotagent-ul/pull/474 I understand this issue can be closed
