### ISSUE TITLE
Different service/subservice for same topics in "Device not found for topic" warning logs in iota-ul

### ISSUE THREAD

**Issue by smartcitydevops** [telefonicaid/iotagent-ul#508]
In https://github.com/telefonicaid/iotagent-json/issues/587 we have commented an issue for iota-json. The same issue happens in iota-ul

The logs are very similar

time=2021-08-18T11:41:04.888Z | lvl=WARN | corr=n/a | trans=n/a | op=IOTAUL.Common.Binding | from=n/a | srv=srvice1 | subsrv=/subservice1| msg=MEASURES-004: Device not found for topic [/8vpv6nawjyqcdsfto8to2debn/Device:WA4FA7H7M9/attrs] | comp=IoTAgent

time=2021-08-18T06:30:17.991Z | lvl=WARN | corr=f7ca2d56-df5c-47de-a327-b7b3049494d5 | trans=f7ca2d56-df5c-47de-a327-b7b3049494d5 | op=IOTAUL.Common.Binding | from=n/a | srv=service2| subsrv=/subservice2| msg=MEASURES-004: Device not found for topic [/8vpv6nawjyqcdsfto8to2debn/Device:WA4FA7H7M9/attrs] | comp=IoTAgent

Please note that for both iota-ul and iota-json similar warn logs with srv=n/a and subsrv=n/a are found (even though the are not the most frequent)

**Comment by AlvaroVega** [comment]
Both cases "n/a" is the proper service and subservice

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/iotagent-ul/pull/512
