### ISSUE TITLE
Docker is not published in dockerhub

### ISSUE THREAD

**Issue by jmcanterafonseca** [telefonicaid/iotagent-ul#56]
despite doc says you can run fiwareiotplatform/iotagent-ul reality is that there is nothing with that name published in dockerhub

**Comment by dmoranj** [comment]
The repository name is wrong in the documentation. It should be either
"fiware" or "telefonicaiot".

**Comment by jmcanterafonseca** [comment]
is the account 'fiwareiotplatform' obsolete?, if so, we should remove it to
avoid confusion

2016-05-10 20:26 GMT+02:00 Daniel Moran <notifications@github.com>:

**Comment by dmoranj** [comment]
Agree. It's obsolete and I always have problems remembering the right one. I'll speak with the rest of developers of the involved projects to remove it from DockerHub

**Comment by jmcanterafonseca** [comment]
great

2016-05-11 11:42 GMT+02:00 Daniel Moran <notifications@github.com>:

**Comment by dmoranj** [comment]
The developers of the components deployed on that organization have been told to remove them ASAP, and there is already PR fixing the documentation, so I'm closing the ticket.
