### ISSUE TITLE
Question: How to enable NGSIv2 in iotagent-ul helmchart?

### ISSUE THREAD

**Issue by sfl0r3nz05** [telefonicaid/iotagent-ul#579]
Hi, I received `{"name":"BAD_REQUEST","message":"Request error connecting to the Context Broker: 501"}` error when when I send a POST to *iotagent-ul* deployed via *iotagent-ul* helm chart.

I get the following log via `kubectl logs pod/iotagent-ul-xxxxxx`:

```console
time=2022-10-08T09:03:18.182Z | lvl=DEBUG | corr=d7ed414d-a132-45ea-b4a3-38ee14a828dc | trans=d7ed414d-a132-45ea-b4a3-38ee14a828dc | op=IoTAgentNGSI.Request | from=n/a | srv=openiot | subsrv=/ | msg=Response {
    "error": "NotImplemented",
    "description": "Only NGSIv1-based forwarding supported at the present moment. Set explictely legacyForwarding to true"
}
```

Following the [iotagent-ul documentation](https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/installationguide.md#global-configuration) to enable NGSIv2 it must be set `ngsiVersion` in **contextBroker**:

```console
{
    host: '192.168.56.101',
    port: '1026',
    ngsiVersion: 'v2'
}
```

So, I have modified:

- *Chart.yaml*

```console
{
  contextBroker:
    # -- host of the broker
    host: orion
    # -- port of the broker
    port: 1026
    # to use NGSI v2
    ngsiVersion: v2
}
```

-  *configmap.yaml*

```console
contextBroker: {
            /**
             * Host where the Context Broker is located.
             */
            host: '{{ .Values.iota.contextBroker.host }}',

            /**
             * Port where the Context Broker is listening.
             */
            port: '{{ .Values.iota.contextBroker.port }}'
            
            /**
             * If you want to use NGSI v2.
             */
            ngsiVersion: '{{ .Values.iota.contextBroker.ngsiVersion }}'
        }
```

However, the error persists, any suggestions on how to properly configure NGSIv2?

**Comment by fgalan** [comment]
It seems this question has been already published at SOF at https://stackoverflow.com/questions/74003335/how-to-enable-ngsiv2-in-iotagent-ul-helmchart

Thus, I'd suggest to close the issue and continue the discussion there. Issues in github repository are for bug, features, etc. but not for question or support, that should be done in SOF.

Thanks!
