### ISSUE TITLE
constants.DEFAULT_ATTRIBUTE_TYPE is string instead of Text

### ISSUE THREAD

**Issue by pooja1pathak** [telefonicaid/iotagent-ul#664]
Twin issue for IoTAgent-UL as IoTAgent-JSON [#810](https://github.com/telefonicaid/iotagent-json/issues/810) as per [comment](https://github.com/telefonicaid/iotagent-json/pull/813#issuecomment-1920653326)

**Comment by fgalan** [comment]
I understand that after merging PR #665 this issue can be closed.
