### ISSUE TITLE
change timestamp to true in provisionDeviceProduction.json to work with changes in node-lib PR#1580

### ISSUE THREAD

**Issue by pooja1pathak** [telefonicaid/iotagent-ul#666]
change timestamp to true in https://github.com/telefonicaid/iotagent-ul/blob/master/test/deviceProvisioning/provisionDeviceProduction.json as discussed in: https://github.com/telefonicaid/iotagent-node-lib/pull/1580#issuecomment-1956955107

**Comment by KeshavSoni2511** [comment]
Hi, I am working on it

**Comment by fgalan** [comment]
I understand this issue is fixed by PR https://github.com/telefonicaid/iotagent-ul/pull/667

@pooja1pathak could this issue be closed?
