### ISSUE TITLE
Error 404 when sending measurements with HTTP transport.

### ISSUE THREAD

**Issue by dmabtrg** [telefonicaid/iotagent-ul#67]
Hi,

I've been testing this new IoT agent to replace the old one in [tutorials.TourGuide-App](https://github.com/Fiware/tutorials.TourGuide-App).  I'm using the ultralight protocol with the HTTP transport and was using the [Figway tools](https://github.com/telefonicaid/fiware-figway) for a simple client.  With the new agent, the service and device creation seems to work fine (no errors and the entities appear in mongo), but when trying to send a measurement, it fails with the following error:

```
data:    bin/iotagent-ul:17 - time=2016-05-17T11:06:47.034Z | lvl=DEBUG | corr=a48b1755-9002-4684-a984-453e2feb93fa | trans=a48b1755-9002-4684-a984-453e2feb93fa | op=IoTAgentNGSI.RestUtils | srv=testul20 | subsrv=/ | msg=Error [SyntaxError] handing request: Unexpected token t
data:    bin/iotagent-ul:17 - time=2016-05-17T11:06:47.034Z | lvl=DEBUG | corr=a48b1755-9002-4684-a984-453e2feb93fa | trans=a48b1755-9002-4684-a984-453e2feb93fa | op=IoTAgentNGSI.RestUtils | srv=testul20 | subsrv=/ | msg=response-time: 1
```

and this is the message received in the client:

```
* Asking to http://iota:4041/iot/d?k=devguideiot&i=ul20client_ACPI_0_Thermal
* Headers: {'Fiware-Service': 'testul20', 'content-type': 'application/json', 'Fiware-ServicePath': '/', 'X-Auth-Token': 'NULL'}
* Sending PAYLOAD: 
t|65.0

...

* Status Code: 500
* Response: 
{"name":"SyntaxError","message":"Unexpected token t"}
```

I saw issue #57 addresses this error, so I tried with the develop branch and updated the content-type of the scripts to use `text/plain` and/or `application/text`.  Now I get the following error:

```
data:    bin/iotagent-ul:17 - time=2016-05-17T11:07:07.213Z | lvl=DEBUG | corr=37d6d401-43c5-4bac-bd5d-d1b5881dcbb6 | trans=37d6d401-43c5-4bac-bd5d-d1b5881dcbb6 | op=IoTAgentNGSI.RestUtils | srv=testul20 | subsrv=/ | msg=Request for path [/iot/d] from [iota:4041]
data:    bin/iotagent-ul:17 - time=2016-05-17T11:07:07.213Z | lvl=DEBUG | corr=37d6d401-43c5-4bac-bd5d-d1b5881dcbb6 | trans=37d6d401-43c5-4bac-bd5d-d1b5881dcbb6 | op=IoTAgentNGSI.RestUtils | srv=testul20 | subsrv=/ | msg=Unrecognized body type application/text
data:    bin/iotagent-ul:17 - time=2016-05-17T11:07:07.214Z | lvl=DEBUG | corr=37d6d401-43c5-4bac-bd5d-d1b5881dcbb6 | trans=37d6d401-43c5-4bac-bd5d-d1b5881dcbb6 | op=IoTAgentNGSI.RestUtils | srv=testul20 | subsrv=/ | msg=response-time: 1
```

and the client receives:

```
* Asking to http://iota:4041/iot/d?k=devguideiot&i=ul20client_ACPI_2_Thermal
* Headers: {'Fiware-Service': 'testul20', 'content-type': 'application/text', 'Fiware-ServicePath': '/', 'X-Auth-Token': 'NULL'}
* Sending PAYLOAD: 
t|25.0

...

* Status Code: 404
* Response: 
Cannot POST /iot/d?k=devguideiot&amp;i=ul20client_ACPI_2_Thermal
```

Using `text/plain` gives the same error.

Is this a bug in the agent or has there been any other change in the protocol that I must be aware of?

Thanks.

**Comment by dmoranj** [comment]
The problem is the port you are using. Node.js based IoT Agents use different ports for the Southbound and Northbound APIs. You are using port 4041 to send the measures, the same one you used for provisioning the device, but you should be using the HTTP binding port instead. 

On the other hand, the appropriate Content Type is text/plain, as I think it was explained in that issue.

**Comment by dmabtrg** [comment]
You're right.  Changing the port to 7896 when sending the measurements works.  The weird thing was that this was working with the old agent, using the same port for registering services/devices and sending measurements, and that that was what I found in the examples of the documentation.

Thanks.
