### ISSUE TITLE
Readme shows "iot/d" instead of "iot/ul" path

### ISSUE THREAD

**Issue by XavierVal** [telefonicaid/iotagent-ul#96]
To users that want to specify a different defaultResource for the agents instead of use the same for all the agents

https://github.com/telefonicaid/iotagent-ul/blob/develop/README.md#http-binding

Related to: 
https://github.com/telefonicaid/iotagent-json/issues/150

**Comment by Keshav-NEC** [comment]
Hi @fgalan Do we need to do change the file for this. As I investigated, I was able to get services and devices while giving iot/ul instead of iot/d if i setup service group with iot/ul. Please let me know so that I can do the needful. Thanks

**Comment by fgalan** [comment]
Looking to the [sister issue](https://github.com/telefonicaid/iotagent-json/issues/150), that one was closed time ago (year 2018) so I think is good idea to close also this one.

With regards to resource-related issue, I think we can continue discussion on https://github.com/telefonicaid/iotagent-ul/issues/590

**Comment by mapedraza** [comment]
@Keshav-NEC if you are still interested to keep on working in this, issue #590 is still open and is more detailed
