### ISSUE TITLE
No timeout defined for HTTP commands

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/iotagent-ul#97]
Copied from https://github.com/telefonicaid/iotagent-node-lib/issues/373.

It should be defined a timeout for commands responses.

Also it would be nice to change the status of the command in case the commnad endpoint does not respond

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/iotagent-ul/pull/323

**Comment by fgalan** [comment]
@Jagatjot does IOTA-JSON agent (https://github.com/telefonicaid/iotagent-json) has a similar configuration parameter?

**Comment by fgalan** [comment]
> does IOTA-JSON agent (https://github.com/telefonicaid/iotagent-json) has a similar configuration parameter?

The corresponding issue in IOTA-JSON repository is https://github.com/telefonicaid/iotagent-json/issues/152 and needs to be addressed.
